### ISSUE TITLE
irc-disentanglement/tools/ empty

### ISSUE THREAD

**Issue by basma-b** [jkkummerfeld/irc-disentanglement#1]
@jkkummerfeld can you please check the irc-disentanglement/tools/ folder which is empty ?

**Comment by jkkummerfeld** [comment]
Yes, this is just a placeholder for the moment (note that the data folder is empty too). Sorry!

**Comment by basma-b** [comment]
An when shall we be able to download data ?

**Comment by jkkummerfeld** [comment]
Following up here as well as via email for other people who come across this - for now please email me if you would like access to the data. I will update this repository as soon as the paper is published.
