### ISSUE TITLE
majority vote for graph inconsistent with paper?

### ISSUE THREAD

**Issue by raaupr** [jkkummerfeld/irc-disentanglement#3]
Hi, I was trying to reproduce your results in the paper, and I might be wrong, but it seems that this part of the code from `majority_vote.py` (54-58) is inconsistent with what's mentioned in the paper?
``` python
        if options[0][0] >= MIN_AGREE:
            if options[0][1] != src:
                keep = [n for c, n in options if c >= MIN_AGREE and n != src]
        elif options[0][1] != src:
            keep = [options[0][1]]
```
In the paper you said:
> ... combine output by keeping the edges they all agree on. Link messages with no agreed antecedent to themselves.

In the code, it seems that you:
1. do not keep the edges that all agree on if they are self-links, and
2. if there's no agreed antecedent, you link it to the most-voted link IF the most-voted one is not a self-link?

As a result, I wasn't able to reproduce the results reported on your paper.

**Comment by jkkummerfeld** [comment]
Thanks for raising this. There are two things going on:
- Handling self-links. While this code looks like self-links are dropped, what actually happens is that it leaves that line with no antecedent, which then becomes a self-link in post-processing.
- If no antecedent is agreed upon, the most common option is returned. You are correct that the description in the paper does not accurately reflect that.

Sorry for the mistake in the paper and the unclear handling of self-links. Hopefully by following the code you get the same results - please share a follow-up here if you do not.

I'll put together a nice fix and update to the website, but not until after the Thanksgiving holiday.

**Comment by raaupr** [comment]
Thank you so much for clarifying this!

I actually haven't been able to evaluate the results using your scripts as-is. I have been modifying the code to make it work, using your paper as a reference to understand what needs to happen, and I might have been able to reproduce your results (very close to it least). But I'm afraid I might miss some subtleties that aren't mentioned in your paper (such as the most-voted one above).
Again, perhaps this is me not knowing how to use the scripts correctly, apologies. 

Example of problems:

**Formatting**

the format of the output of the inference is:
```
data/test/2005-07-06_14.annotation.txt:1000 997 -
```
Then, using the `output-from-py-to-graph.py`, the output became:
```
2005-07-06_14.annotation.txt:1000:997 -
```
Then, using the `majority_vote.py`, I get an error:
``` bash
Traceback (most recent call last):
  File "src/majority_vote.py", line 15, in <module>
    name, values = line.strip().split(":")
ValueError: too many values to unpack (expected 2)
```

**Evaluating**

And if I use the result of the `output-from-py-to-graph.py` on the inference output directly:
```bash
$ python tools/evaluation/graph-eval.py --gold data/test/*annotation* --auto output/example-run-1.test.out
Traceback (most recent call last):
  File "tools/evaluation/graph-eval.py", line 52, in <module>
    get_pairs(filename, auto)
  File "tools/evaluation/graph-eval.py", line 15, in get_pairs
    nums = [int(n) for n in line.split() if n != '-']
  File "tools/evaluation/graph-eval.py", line 15, in <listcomp>
    nums = [int(n) for n in line.split() if n != '-']
ValueError: invalid literal for int() with base 10: '#'
```
and using the `.graphs` input:
```
$ python tools/evaluation/graph-eval.py --gold data/test/*annotation* --auto output/example-run-1.test.out.graphs
g/a/m: 5187 5000 0
p/r/f: 0.0 0.0 0.0
```

**Comment by jkkummerfeld** [comment]
Thanks for the detailed follow up.

The format conversion steps you showed were broken. I had changed the main `disentangle.py` code to produce something slightly different from what `output-from-py-to-graph.py` expected. Any downstream processing would fail as a result.

I've pushed an update (5355185be77b61779a9f6616695f0c5abdedd1ee) that should fix these issues. I'm closing this issue for now, but please do reopen it / a new one if you have further issues.
