### ISSUE TITLE
Annotations to cluster for "conversation-eval"

### ISSUE THREAD

**Issue by maxzzze** [jkkummerfeld/irc-disentanglement#4]
I converted the output (auto) to graphs with `output-from-py-to-graph.py` and then to clusters with `graph-to-cluster.py`. 

I am now attempting to use the `conversation-eval.py` file to get cluster metrics but I am running into an issue finding how to create the `gold` file which is input to this script. What would be the proper way to convert the annotation files to "gold clusters"?

Thank for any help.

**Comment by jkkummerfeld** [comment]
You should be able to apply the same `graph-to-cluster.py` script to the gold data to then use for evaluation.

**Comment by jkkummerfeld** [comment]
I've just pushed a commit (76c3daa1d44d6d5576eba7d2844eae400633d8ec) that adds a convenient form of the gold annotations in the data directory with the clustering step done.

I'm going to close this, but please re-open it if you still have trouble!
