### ISSUE TITLE
About Annotations

### ISSUE THREAD

**Issue by lsyysl9711** [jkkummerfeld/irc-disentanglement#5]
Hello! Your work is great, but I am confused about the annotations:

In the readme file of data file folder, you give one example from the files of the form `2007-12-17.train-a.* and the corresponding annotations are 993 1000 -.

But when I use python to process raw/ascii/tok file, the line at 992 is not  '[03:41] <ubotu> amitprakash...'. I also use my VSCode to check these txt files and I think these problems are caused by "when to start a new line": In your given example, the response from 'ubotu' is split into six lines while in the raw/ascii/tok file there is only one line for this response. 

So I would like to know how to fix these disorders or if I misunderstand anything.

Thanks,

**Comment by lsyysl9711** [comment]
I think I made a stupid question, I know where I made a misunderstanding...

Please ignore this issue (:

**Comment by jkkummerfeld** [comment]
Glad you figured it out. For anyone else who comes across this in the future, note that the data in the README file is just 3 lines from each file. The annotation `993 1000 -` actually refers to these two lines:

993 - https://github.com/jkkummerfeld/irc-disentanglement/blob/35f0a40eb0abc24ae0116bb9f570d11492880b4d/data/train/2007-12-17.train-a.ascii.txt#L994

1000 - https://github.com/jkkummerfeld/irc-disentanglement/blob/35f0a40eb0abc24ae0116bb9f570d11492880b4d/data/train/2007-12-17.train-a.ascii.txt#L1001

Note also that the annotations use 0-indexing, but the lines in Github show 1-indexing.
